### ISSUE TITLE
Don't need to Skip MattressItem in deleting Store Mapping for category

### ISSUE THREAD

**Issue by aquaristar** [abcwarehouse/nop#18]
https://github.com/abcwarehouse/nop/blob/dc8d3d27fa91f618944f0721d6bfca6daf5f4d54/src/Plugins/Nop.Plugin.Misc.AbcSync/Tasks/CoreUpdate/ImportProductCategoryMappingsTask.cs#L126

In the above code line I don't think that the {mattressItemAddition} should be added in there.

**Comment by dfar-io** [comment]
So with the way mattresses are synced (they are synced on their own schedule, not on the overall sync process), we want to make sure we don't delete the Store Mappings related to mattresses, or else when the normal sync process happens, the mattresses won't be synced to any stores and won't be visible until their next run.

Ideally, we'd set up ImportProductCategoryMappingsTask.cs to not clear out the entire table, and just sync the deltas for each product instead.

**Comment by aquaristar** [comment]
var mattressItemAddition = _importSettings.SkipOldMattressesImport ?
                " AND EntityId NOT IN (SELECT ProductId FROM [AbcMattressModel])" :
                "";
{mattressItemAddition} option is to exclude Mattress product id list for removing store mapping.
It's already performed in this line.
https://github.com/abcwarehouse/nop/blob/dc8d3d27fa91f618944f0721d6bfca6daf5f4d54/src/Plugins/Nop.Plugin.Misc.AbcSync/Tasks/CoreUpdate/ImportProductCategoryMappingsTask.cs#L188

For Removing CategoryStoreMapping It dosen't require to use in there.

**Comment by dfar-io** [comment]
So those are two different tables:
- StoreMappings - maps the product to a specific store (StoreMapping)
- ProductCategoryMappings - maps the product to a specific category (Product_Category_Mapping)

We need both to be able to function, and ideally, both would only merge changes instead of clearing the tables completely in the sync process. Do you see any other issue?

**Comment by aquaristar** [comment]
I know there are two different tables.
"DELETE FROM StoreMapping where EntityName = 'Category' {mattressItemAddition}; UPDATE Category set LimitedToStores = 1;"
StoreMapping have many kinds of mapping data such as ProductStoreMapping, CategoryStoreMapping, and so on.
What my question mean is why do you compare AbcMattressModel product id and Category Id for remvoing category store mappings in StoreMapping table.

**Comment by aquaristar** [comment]
When you run this query "DELETE FROM StoreMapping where EntityName = 'Category' " then those EntityId are only CategoryId, right?
But in this additional query " AND EntityId NOT IN (SELECT ProductId FROM [AbcMattressModel])" the EntityId is ProductId.

**Comment by dfar-io** [comment]
You are right - my apologies. With it checking on the ProductId for Category, I'm sure the code has been doing nothing, so I'll remove it. Thanks for finding it.
