### ISSUE TITLE
Fullstaging _> ImportProductWarrantyMapping require to filter duplicated items

### ISSUE THREAD

**Issue by aquaristar** [abcwarehouse/nop#22]
https://github.com/abcwarehouse/nop/blob/b95181f12f49d09dd489c9a93ea23fec85e4a169/src/Plugins/Nop.Plugin.Misc.AbcSync/Tasks/FillStaging/FillStagingWarrantiesTask.cs#L204

This function results have many duplicated rows. Please check StagingDb -> ProductWarrantyGroupMapping

**Comment by dfar-io** [comment]
As syncing has moved over to Python codebase, this is irrelevant
