### ISSUE TITLE
AbcSync Plugin -> ImportProduct.cs : ProductManufacturerMapping logic have problem.

### ISSUE THREAD

**Issue by aquaristar** [abcwarehouse/nop#3]
Hi John, Dave,
I think this inserting product manufacturer mapping logic have bugs generating pcm rows with wrong ProductId=0 in [Product_Manufacturer_Mapping] table for the cases when import new product.
Please check following codes.
https://github.com/abcwarehouse/nop/blob/6f4fbbdd69aca3e3dff3f9912eb85d160b73f447/Plugins/Nop.Plugin.Misc.AbcSync/Tasks/CoreUpdate/ImportProductsTask.cs#L216-L230

**Comment by dfar-io** [comment]
Moved this call to after the insert/update of a product to ensure we don't have a null value for the Product ID.
